sudo: required
language: python

services:
  - docker

before_install:
  - docker build -t ernakulgoyal/travis-flask-ci -f Dockerfile .

script:
  - python -m pytest -v

#deploy:
#  provider: elasticbeanstalk
#  region: 'us-east-1'
#  app: 'docker'
#  env: 'docker-env'
#  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
#  bucket_path: 'docker'
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY
