sudo: required
language: python

services:
  - docker

before_install:
  - docker build -t ernakulgoyal/travis-flask-ci -f Dockerfile .

script:
  - python -m pytest -v

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'travis-flask-ci'
  env: 'Travisflaskci-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-893686199282'
  bucket_path: 'travis-flask-ci'
  on:
    branch: main
  access_key_id: $AWS_ACCESSKEY
  secret_access_key: $AWS_SECRETKEY
